### ISSUE TITLE
Missing optimization information on methods OnEntry and OnExit

### ISSUE THREAD

**Issue by todthomson** [haacked/NullGuard#3]
Hey Phil,

Just installed Postsharp 2.1 from the nuget package and then installed your NullGuard package.

As I add the [EnsureNonNullAspect] aspect at either the class or method level I immediately get the following compiler warnings:

```
Warning 1   Missing optimization information on method 'NullGuard.PostSharp.EnsureNonNullAspect.OnEntry(PostSharp.Aspects.MethodExecutionArgs)'.
            This information is computed automatically by PostSharp.
            Make sure that assembly NullGuard.PostSharp is processed by PostSharp.
Warning 2   Missing optimization information on method 'NullGuard.PostSharp.EnsureNonNullAspect.OnExit(PostSharp.Aspects.MethodExecutionArgs)'.
            This information is computed automatically by PostSharp.
            Make sure that assembly NullGuard.PostSharp is processed by PostSharp.
```

It could be that this is nothing to worry about, but a) I don't like compiler warnings that I can't find the answer to anywhere on Google b) it could be something to worry about.

Any help would be most appreciated.

Cheers!

Tod.

**Comment by mgroves** [comment]
I can reproduce this as well.

But, it looks like there may be some performance changes that already addressed these warnings, but it's just not deployed to NuGet yet, since "OnExit" isn't even being used in EnsureNonNullAspect anymore.

**Comment by todthomson** [comment]
I'll compile from source and see how I go and report back here.

**Comment by todthomson** [comment]
So I just pulled the latest source from GitHub and I'm getting the same warnings still (just applied to OnEntry and OnSuccess as you predicted).

I'm happy to fix it and submit a pull request if I can work out the cause... No amount of Google-fu has helped me thus far so any assistance would be much appreciated :)

**Comment by gfraiteur** [comment]
The reason is in the error message: library NullGuard.PostSharp has not been processed by PostSharp.

**Comment by mgroves** [comment]
But that library doesn't need to be processed by PostSharp, since it contains the aspects? The code that you use the NullGuard aspects _on_ is the one that needs to be processed. If that's the case, then I think it's safe to disregard these warnings.

**Comment by gfraiteur** [comment]
Yes, it needs to be processed, because during processing PostSharp adds optimizing information to the aspect. This is how the aspect optimizer works. The warning will appear if (1) you compile using PostSharp Pro or Trial and (2a) the library was not processed by PostSharp or (2b) the library was processed by PostSharp Express/Starter.

**Comment by todthomson** [comment]
Right. So all I have done is (1) Create a new project in Visual Studio (2) Use NuGet to install PostSharp 2.1 (3) Use NuGet to install NullGuard (4) Create SomeClass with SomeMethod and add the [EnsureNonNullAspect] to the class or method.

So I suspect that I am hitting (2a) or (2b) but I have no idea how to get around it, so I'll look into it further and report back. I suspect it's just that I'm mixing and matching Pro (Trial) with the Express / Starter DLL.

**Comment by todthomson** [comment]
Closing (this is ancient). You can reopen if you ever care to.
